version: "3.8"

services:
  webapi:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8009:8000
    environment:
      - database=postgres
      - DJANGO_SETTINGS_MODULE=config.settings.settings_local
    depends_on:
      - webapi-db
  webapi-db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testuser
      - POSTGRES_DB=address_test

volumes:
  postgres_data:
