version: "3.8"

services:
  webapi:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./.env.dev
    depends_on:
      - webapi-db
  webapi-db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=address
      - POSTGRES_PASSWORD=address
      - POSTGRES_DB=address_dev

volumes:
  postgres_data:
