# Generated by Django 3.2.6 on 2021-08-31 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_remove_user_user_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['id']},
        ),
    ]
