# Generated by Django 3.2.6 on 2021-08-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_user_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user_uuid',
            field=models.UUIDField(default=123, editable=False),
            preserve_default=False,
        ),
    ]
