# Generated by Django 3.2.6 on 2021-08-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_address_user_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user_uuid',
        ),
    ]
