# Generated by Django 3.2.6 on 2021-08-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_alter_address_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=3),
        ),
    ]
